# Generated by Django 5.0.4 on 2024-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('service', 'Service'), ('project', 'Project'), ('courses', 'Courses')], max_length=10),
        ),
    ]
