# Generated by Django 5.0.4 on 2024-05-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_u',
            name='object',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
