# Generated by Django 5.0.4 on 2024-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
