# Generated by Django 5.0.4 on 2024-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_teammember_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_u',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='write about vision'),
        ),
        migrations.AlterField(
            model_name='about_u',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=500),
        ),
    ]
