# Generated by Django 5.0.4 on 2024-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skuId',
            field=models.IntegerField(max_length=100),
        ),
    ]
