# Generated by Django 5.0.4 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
